language: php

php:
  - 7.0

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

sudo: false

install:
    - composer self-update
    - composer install --no-interaction --prefer-source
    - cp .env.travis .env
    - mkdir -p storage/app/images/large
    - mkdir -p storage/app/images/medium
    - mkdir -p storage/app/images/original
    - mkdir -p storage/app/images/small
    - mkdir -p storage/app/images/small_square
    - mkdir -p storage/app/images/xsmall_square
    - chmod -R o+w storage/
    - mysql -e 'create database IF NOT EXISTS trip2;'

before_script:
    - php artisan migrate:refresh

script: phpunit

notifications:
    email: false
    slack: tripikad:Rb20AN0r1arWwhxIBl9DNaZ5